service: codechallenge-lbd-get

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
#- serverless-esbuild
  - serverless-offline

functions:
  api:
    handler: dist/serverless.handler
#    handler: src/serverless.handler
    events:
      - http:
          path: /{proxy+}
          method: any

package:
  individually: true
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**